BakeryWebSite/Models/CategoryGood.cs
namespace BakeryWebSite.Models
{
    public class CategoryGood
    {
        public List<Category> Category { get; set; }
        public List<Good> Goods { get; set; }
    }
}   

BakeryWebSite/Models/Good.cs
namespace BakeryWebSite.Models
{
    public class Good
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price{ get; set; }
        public string Image { get; set; }
        public int Categories_Id { get; set; }
        public int Weight {  get; set; }
        public Good(string name, double price, string image, int categoryId, int weight) 
        {
            Name = name;
            Price = price;
            Image = image;
            Categories_Id = categoryId;
            Weight = weight;
        }
        public Good() { }
    }
}

BakeryWebSite/Controllers/GoodController.cs
using BakeryWebSite.Models;
using Microsoft.AspNetCore.Mvc;
using System.Xml.Linq;

namespace BakeryWebSite.Controllers
{
    public class GoodController : Controller
    {
        private BakeryContext db;
        public GoodController(BakeryContext context) 
        {
            db = context;
        }
        public ActionResult Main()
        {
            CategoryGood cg = new CategoryGood();
            using (db)
            {
                cg.Category = db.Categories.ToList<Category>();
                cg.Goods = db.Goods.ToList<Good>();
                if (Policy.Authorized)
                {
                    ViewBag.auth = "Выйти";
                    return View(cg);
                }
            }
            ViewBag.auth = "Войти";
            return View(cg);
        }
        public ActionResult CategoryGoods(int id)
        {
            CategoryGood cg = new CategoryGood();
            using (db)
            {
                cg.Category = db.Categories.ToList<Category>();
                cg.Goods = db.Goods.Where(item => item.Categories_Id == id).ToList();
                if (Policy.Authorized)
                {
                    ViewBag.auth = "Выйти";

                    return View(cg);
                }
            }
            ViewBag.auth = "Войти";
            return View(cg);
        }

        public ActionResult Good(int id)
        {
            GoodComponent gc = new GoodComponent();
            using (db)
            {
                gc.Good = db.Goods.Find(id);
                gc.Components = new List<Component>();
                List<Composition> composition = db.Composition.Where(item => item.Goods_Id == id).ToList();
                foreach(Composition c in composition) {
                    gc.Components.Add(db.Components.Find(c.Components_Id));
                }
            }
            ViewBag.auth = "Продукция";
            return View(gc);
        }

    }
}

BakeryWebSite/Controllers/OrderController.cs
using BakeryWebSite.Models;
using Microsoft.AspNetCore.Mvc;

namespace BakeryWebSite.Controllers
{
    public class OrderController : Controller
    {
        private BakeryContext db;
        public OrderController(BakeryContext context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        public ActionResult Basket()
        {
            User user = new User();
            using (db)
            {
                if (Policy.Authorized)
                {
                    ViewBag.auth = "Продукция";
                    user = db.Users.Find(Policy.userid);

                    return View(user);
                }
            }
            ViewBag.auth = "Продукция";
            return View("~/Views/User/Login.cshtml");
        }
        public ActionResult Order()
        {
            User user = new User();
            using (db)
            {
                if (Policy.Authorized)
                {
                    ViewBag.auth = "Продукция";
                    user = db.Users.Find(Policy.userid);

                    return View(user);
                }
            }
            ViewBag.auth = "Продукция";
            return View("~/Views/User/Login.cshtml");
        }
    }
}

BakeryWebSite/Controllers/UserController.cs
using BakeryWebSite.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Security.Cryptography;
using System.Xml.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BakeryWebSite.Controllers
{
    public class UserController : Controller
    {
        BakeryContext db;
        public UserController(BakeryContext context)
        {
            db = context;
        }
        public string GetHashString(string s)
        {
            byte[] bytes = Encoding.Unicode.GetBytes(s);
            MD5CryptoServiceProvider CSP = new MD5CryptoServiceProvider();
            byte[] byteHash = CSP.ComputeHash(bytes);
            string hash = "";
            foreach (byte b in byteHash)
            {
                hash += string.Format("{0:x2}", b);
            }
            return hash;
        }
        public IActionResult Login()
        {
            Policy.Authorized = false;
            ViewBag.auth = "Продукция";
            return View();
        }
        
        [HttpPost]
        public IActionResult Login(string login, string password)
        {
            using (db)
            {
                CategoryGood cg = new CategoryGood();
                cg.Category = db.Categories.ToList<Category>();
                cg.Goods = db.Goods.ToList<Good>();
                foreach (User item in db.Users)
                {
                    if (item.Login == login)
                    {
                        if (item.Password == GetHashString(password))
                        {
                            if (item.Role == "Клиент")
                            {
                                Policy.userid = item.Id;
                                Policy.Authorized = true;
                                string name = db.Users.Find(Policy.userid).Name;
                                ViewBag.auth="Выйти";
                                return View("~/Views/Good/CategoryGoods.cshtml", cg);
                            }
                        }
                    }
                }
            }
            ViewBag.profile = "";
            ViewBag.auth = "Продукция";
            return View();
        }
        public IActionResult SignUp()
        {
            ViewBag.auth = "Продукция";
            return View();
        }
        [HttpPost]
        public IActionResult SignUp(string login, string password, string surname, string name, string email, string phone)
        {
            using (db)
            {
                CategoryGood cg = new CategoryGood();
                cg.Category = db.Categories.ToList<Category>();
                cg.Goods = db.Goods.ToList<Good>();
                foreach (User item in db.Users)
                {
                    if (item.Login == login)
                    {
                        return View();
                    }
                }
                User user = new User(login, GetHashString(password), email, "Клиент", phone, name, surname, "");
                db.Users.Add(user);
                db.SaveChanges();
                Policy.userid = user.Id;
                ViewBag.auth = "Выйти";
                return View("~/Views/Good/CategoryGoods.cshtml", cg);
            }
        }
    }
}

BakeryWebSite/Views/Good/CategoryGoods.cshtml
@model BakeryWebSite.Models.CategoryGood
@section SignUpBtn{
    <a style="text-decoration: none; font-size: 18px" asp-controller="Good" asp-action="Main">
        @ViewBag.auth
    </a>
}

<link rel="stylesheet" href="~/css/Main.css" />
<div class="contentdiv">
    <div id="categoriesdiv" class="titlediv">
        <div class="outdiv">
            @foreach (Category cat in Model.Category)
            {
                <div class="categories">
                    @Html.ActionLink(cat.Name, "CategoryGoods", "Good", new{id=cat.Id})
                    @*                     <a asp-area="" asp-controller="Good" asp-action="Main" id="@cat.Id">
                @cat.Name
                </a> *@
                </div>
            }
        </div>
    </div>

    <div id="goodsdiv" class="titlediv">
        @foreach (var good in Model.Goods)
        {
            <div class="gooddiv">
                <div class="imgdiv">
                    <img class="img" src="../../@good.Image" alt="@good.Name" />
                </div>
                @Html.ActionLink(good.Name, "Good", "Good", new{id=good.Id}, new {@style="color: black; text-decoration: none; font-weight: bold;"})
                <p class="good_weight">@good.Weight</p>
                <p class="good_price">
                    <span>
                        @good.Price
                    </span>
                    <span>руб.</span>
                </p>
            </div>
        }



    </div>
    <div id="addressdiv" class="titlediv">
        <p><a href="@Url.Action("Basket", "Order")">Корзина</a></p>
    </div>
    @*     <script>
        document.getElementById('showMenuButton').addEventListener('click', function () {
            var menu = document.getElementById('menu');
            if (menu.style.display === 'none') {
                menu.style.display = 'block';
            } else {
                menu.style.display = 'none';
            }
        });
    </script> *@
@* </div> *@

BakeryWebSite/Views/Good/Good.cshtml
@model BakeryWebSite.Models.GoodComponent
@{
    ViewData["Title"] = "Товар";
    Layout = "/Views/Shared/_Layout2.cshtml";
}
@section SignUpBtn{
    <a style="text-decoration: none; font-size: 18px" asp-controller="Good" asp-action="Main">
        @ViewBag.auth
    </a>
}

<link rel="stylesheet" href="~/css/Good.css" />
<div style="display: flex; justify-content: center; width: 100%;">
    <div class="maindiv">
            <div style="display: inline-block; width: 50%;">
                <div class="imgdiv">
                    <img class="img" src="../../@Model.Good.Image" />
                </div>
            </div>
            <div class="textdiv">
                <h1 id="goodname">@Model.Good.Name</h1>
                <p>
                    <span>
                        @Model.Good.Weight
                    </span><span>г.</span></p>
                <p>Состав:</p>
                <ul>
                    @foreach(Component c in Model.Components)
                    {
                        <li>@c.Name</li>
                    }
                </ul>
            <p>
                <span id="pricebut">
                        @Model.Good.Price
                    </span><span>руб.</span></p>
            <button onclick="showQuantitySelector()" id="selectbtn" class="roundbut">
                    Выбрать
                </button>

            <div id="quantitySelector" style="display: none;">
                <input type="number" id="quantity" value="1" min="1" max="20" onkeydown="return false">



                <button class="roundbut" onclick="addToCart()">Добавить в корзину</button>
                <a asp-action="Basket" asp-controller="Order">Корзина</a>
            </div>
            </div>
        <script>
            function showQuantitySelector() {
                document.getElementById('quantitySelector').style.display = 'block';
                document.getElementById('selectbtn').style.display = 'none';
            }
            function addToCart() {
                var quantity = document.getElementById('quantity').value;
                var name = document.getElementById('goodname').textContent;
                var price = document.getElementById('pricebut').textContent;
                var selectedProduct = {
                    name: name,
                    price: parseInt(price), // Цена товара
                    quantity: parseInt(quantity)
                };

                // Получаем текущий список товаров из Local Storage
                var cartItems = JSON.parse(localStorage.getItem('cart')) || [];

                // Добавляем выбранный товар в корзину
                cartItems.push(selectedProduct);

                // Сохраняем обновленный список товаров в Local Storage
                localStorage.setItem('cart', JSON.stringify(cartItems)); alert('Товар добавлен в корзину: ' + quantity + ' шт.');
            }
        </script>
    </div>
</div>

BakeryWebSite/Views/Good/Main.cshtml
@model BakeryWebSite.Models.CategoryGood
@section SignUpBtn{
    <a style="text-decoration: none; font-size: 18px" asp-controller="User" asp-action="Login">
        @ViewBag.auth
    </a>
}

<link rel="stylesheet" href="~/css/Main.css" />
<div class="contentdiv">
    <div id="categoriesdiv" class="titlediv">
        <div  class="outdiv">
        @foreach(Category cat in Model.Category)
        {
            <div class="categories">
                    @Html.ActionLink(cat.Name, "CategoryGoods", "Good", new{id=cat.Id})
@*                     <a asp-area="" asp-controller="Good" asp-action="Main" id="@cat.Id">
                @cat.Name
            </a> *@
            </div>
        }
        </div>
    </div>

    <div id="goodsdiv" class="titlediv">
        @foreach(var good in Model.Goods)
        {
            <div class="gooddiv">
                <div class="imgdiv">
                    <img class="img" src="@good.Image" alt="@good.Name" />
                </div>
                @Html.ActionLink(good.Name, "Good", "Good", new{id=good.Id}, new {@style="color: black; text-decoration: none; font-weight: bold;"})
                <p class="good_weight">@good.Weight</p>
                <p class="good_price">
                    <span>
                         @good.Price
                    </span>
                    <span>руб.</span>
                </p>
            </div>
        }

            
        
    </div>
    <div id="addressdiv" class="titlediv">
        <div class="outdiv">
            <p><a href="@Url.Action("Basket", "Order")">Корзина</a></p>
</div>

    </div> 
</div>